bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

#Written by Noe 
from core.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("vendoradmin/", include("vendoradmin.urls")),

    path("ckeditor5/", include('django_ckeditor_5.urls')),
]


# Always serve media files in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static files only needed with DEBUG=True since we're using whitenoise in production
if settings.DEBUG:
    # All the static files are stored in the roots directory in a folder called static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path, include # We need inlcude for paypal integration
from core.views import index, category_list_view, product_list_view, category_product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, add_review
from core.views import search_view, filter_product, add_to_cart, cart_view, delete_item_from_cart, update_cart, checkout, paypalCompletedView, paypalFailedView, createCheckoutSession
from core.views import  dashboard, orderDetail, defaultAddress, wishlistView, addToWishList, removeFromWishlist, contact, ajax_contact_form, save_checkout, vendor_application_form, become_vendor
from core.views import aboutUs, purchasingGuide
app_name = "core"

urlpatterns = [

    # Responsible for creating URL patterns on the browser
    # Example, bookstore.com/hardcover/special

    # We leave the bottom an empty string because we want the  
    # domain alone to direct us to the websites homepage

    # Views for Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),

    # Views for Category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

    # Vendor Views
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendors/<vid>/", vendor_detail_view, name="vendor-detail"),

    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    path("add-review/<pid>/", add_review, name="add-review"),

    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name = "filter-product"),

    #################### Cart Views  #################### 
    # Add to cart URL
    path("add-to-cart/", add_to_cart, name = "add-to-cart"),

    # Cart Page
    path("cart/",cart_view, name = "cart"),

    # Used when deleting items from cart
    path("delete-from-cart/", delete_item_from_cart, name = "delete-from-cart"),

    path("update-cart/", update_cart, name = "update-cart"),


    ####################  CHECKOUT VIEWS ####################
    # Checkout View
    path("checkout/<oid>/", checkout , name = "checkout"),

    # Save Checkout
    path("save_checkout_info/", save_checkout , name = "save_checkout_info"),

    # Additional Checkout: 
    # For stripe
    path("api/create_checkout_session/<oid>/", createCheckoutSession, name="api_checkout_session"),



    #################### Payment Views  #################### 
    # Paypal Views
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('payment-completed/<oid>/', paypalCompletedView, name="payment-completed"),

    path('payment-failed/', paypalFailedView, name="payment-failed"),


    #################### User Info Views  #################### 
    # User Dashboard Views
    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/order/<int:id>', orderDetail, name="order-detail"),
    path("make-default-address/", defaultAddress , name="make-default-address"),


    #################### Wishlists Views  #################### 
    path ("wishlist/", wishlistView, name="wishlist"),
    path("add-to-wishlist/", addToWishList, name="add-to-wishlist"), 
    path("remove-from-wishlist/", removeFromWishlist, name="remove-from-wishlist"), 


    # Contact Views
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),


    path("become-vendor/", become_vendor, name="become-vendor"),
    path("vendor-application-form/", vendor_application_form, name="vendor-application-form"),

    path("about-me/", aboutUs, name="about-me"),
    path("purchasing-guide/", purchasingGuide, name="purchasing-guide"),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

'''
# Inside of Basic URL Patterns you'll see: 
    # 1) Sign-up page
    # 2) Sign-in page
    # 3) Sign-out page

These URL patterns are responsible for the absolute basics of user functionality
'''
urlpatterns = [
    # Basic URL patterns
    path("sign-up/", views.registerView, name="sign-up"),
    path("sign-in/", views.loginView, name="sign-in"),
    path("sign-out/", views.logoutView, name="sign-out"),

    # URL below is responsible for updating user's profile
    path("profile/update/", views.profileUpdate, name="profile-update"),

]

userauths/models.py
# Create your models here.
##################################### READ BELOW ######################################################
# REMINDER: ANYTIME YOU MAKE A CHANGE HERE PLEASE DO THE FOLLOWING
#   1) python manage.py makemigrations
#   2) python manage.py migrate
#######################################################################################################
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


# Define user_directory_path function first
def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id if hasattr(instance, 'user') else 'vendor', filename)

# UserModel 
class User(AbstractUser):
    # We want to make sure that no one is using the same email for another account
    # Therefore we need to imply, unique = True 
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=20)
    bio = models.CharField(max_length=100)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    def __str__(self):
        return self.username
    
# Profile Model
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image", null=True, blank=True)
    full_name = models.CharField(max_length=50, null=True, blank=True)
    bio = models.CharField(max_length=300, null=True, blank=True)
    phone = models.CharField(max_length=30, null=True, blank=True) 
    address = models.CharField(max_length=200, null=True, blank=True) 
    country = models.CharField(max_length=60, null=True, blank=True) 
    verified = models.BooleanField(default=False, null=True, blank=True)
    
    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.bio}"
    
# Contact Us Model 
# We will use this for a contact.html page
# This is where users will contact the website's admin and they have to 
class ContactUs(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=35)
    phone = models.CharField(max_length=15) 
    subject = models.CharField(max_length=30) 
    message = models.TextField()
    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

    def __str__(self):
        return self.full_name
    

# We will use django signals to create a profile for a user when they sign up automatically. 
def create_user_profile(sender, instance, created, **kwargs):   #kwargs is Keyword arguments
    # When a new 
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

 
post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)    

# After the ContactUs model, the becomeVendorForm is likely defined
# Let's fix it to use the user_directory_path function we just defined
class becomeVendorForm(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    business_name = models.CharField(max_length=100)
    business_description = models.TextField()
    vendor_profile_image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    vendor_banner = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Vendor Applications"
        
    def __str__(self):
        return self.business_name    

userauths/forms.py
 # with the help of django forms, it saves us from the headache of using a ton of conditionals
# to create a proper sign up page. 
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username"}))

    # It's important to use .EmailField as it forces the user to input a string ending with @domain.com
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))

    # 
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}))

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Phone"}))

    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone']

userauths/views.py
# Responsible for redirecting users to other pages and rendering the pages
from django.shortcuts import redirect, render
from userauths.forms import UserRegistrationForm, ProfileForm

# Allow user to be logged in automatically into site if signed up
from django.contrib.auth import authenticate, login

#Responsible for logging the user out of their account
from django.contrib.auth import logout

# Responsible for prompting urgent messages
from django.contrib import messages 

from django.conf import settings
# Fix for user login bug
from userauths.models import User, Profile as ProfileModel

# What is the point of this variable? Well if you go to bookstore/settings.py 
# you'll scroll down and find AUTH_USER_MODEL which is connected to "userauths.User"
# We will use this for our try catch 
# User = settings.AUTH_USER_MODEL

# Create your views here.

def registerView(request):

    if request.method == "POST":
        form = UserRegistrationForm(request.POST or None)

        # Responsible for checking if signup data is valid and not malicious data
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")

            # We want to give a quick prompt that the account was created succesfully
            messages.success(request, f"Hey {username}, Your account was created successfully!")
            

            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            login(request, new_user)

            # After logging in the new user, redirect them to the index page
            next_url = request.GET.get("next", 'core:index')
            return redirect(next_url)
    else: 
        form = UserRegistrationForm()

    context = {
        'form': form,
        }
    return render(request, "userauths/sign-up.html", context)

def loginView(request):
    # If a user is already logged in, we want to redirect them to the homepage
    if request.user.is_authenticated:
        messages.warning(request, f"You're already logged in!")
        return redirect("core:index")
    
    if request.method == "POST":
        # Below is basically the same as; email = form = LoginForm(request.POST)
        # It grabs the email the user inputs
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in.")
                next_url = request.GET.get("next", 'core:index')
                return redirect(next_url)
            else: 
                messages.warning(request, "User doesn't exist please create an account.")

        except:
            messages.warning(request, f"User with {email} doesn't exist!")

    return render(request, "userauths/sign-in.html")


def logoutView(request):
      logout(request)
      messages.success(request, "You logged out.")
      return redirect("userauths:sign-in")

def profileUpdate(request):
    profile = ProfileModel.objects.get(user=request.user)
    if request.method == "POST":

        '''
        It's important that we request for POST and Files because we are dealing with user text 
        and user profile image.

            Explanation: 
            request.POST for text
            resquest.FILES for iamge
        '''
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            # Give user capability to make changes in update profile page
            new_form = form.save(commit=False)
            # Ensure that profile is assigned to the correct user 
            new_form.user = request.user
            # Saves any changes to the database
            new_form.save()
            messages.success(request, "Profile Updated Successfully.")
            # Redirect them back to the original dashboard
            return redirect("core:dashboard")
    else:
        form = ProfileForm(instance=profile)

    context = {
        "form": form,
        "profile": profile,
    }

    return render(request, "userauths/profile-edit.html", context)

templates/userauths/profile-edit.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> User <span></span> Update Profile Information
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 m-auto">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="dashboard-menu">
                                    <ul class="nav flex-column" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fi-rs-user mr-10"></i>Profile</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'userauths:sign-out' %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="tab-content account dashboard-content pl-50">
                                    <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="mb-0">Update Profile</h3>
                                            </div>
                                            {% if form.errors %}
                                            <div class="alert-danger alert border">
                                                <strong>{{form.errors}}</strong>
                                            </div>
                                            {% endif %}
                                            <div class="card-body mb-2" style="display: flex; align-items: center; gap: 10px;">
                                                <div>
                                                    {% if profile.image %}
                                                    <span><img src="{{ profile.image.url }}" style="width: 150px; object-fit: cover; border-radius:50%; height:150px;" alt=""></span>
                                                    {% else %}
                                                    <span><img src="https://images.icon-icons.com/1378/PNG/512/avatardefault_92824.png" style="width: 150px; object-fit: cover; border-radius:50%; height:150px;" alt=""></span>
                                                    {% endif %}
                                                </div>
                                                <div>
                                                    <form action="" method="POST" enctype="multipart/form-data">
                                                        {% csrf_token %}
                                                        <div class="mb-4">
                                                            {{form.full_name}}
                                                        </div>
                                                        <div class="mb-4">
                                                            {{form.bio}}
                                                        </div>
                                                        <div class="mb-4">
                                                            {{form.phone}}
                                                        </div>
                                                        <div class="mb-4">
                                                            <label for="{{ form.image.id_for_label }}" class="form-label">Profile Image</label>
                                                            {{form.image}}
                                                        </div>
                                                        <button class="btn btn-success" type="Submit">Save Profile Changes</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
<!--  CORRECTLY COMPLETE -->>
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> User <span></span>Sign In
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                        </div>
                                        <form method="POST">
                                            <!-- Responsible creating a User Session (PREVENTS CROSS-SITE FORGERY [Security]) -->
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required name="email" placeholder=" Enter Email " />
                                            </div>
                                            <div class="form-group">
                                                <input required type="password" name="password" placeholder="Enter Your Password *" />
                                            </div>
                                            <div class="login_footer form-group mb-50">
                                                <a class="text-muted" href="{% url 'core:contact' %}">Forgot password?</a>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
<!--  CORRECTLY COMPLETE -->>
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> User <span></span> Create An Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <!-- Responsible for alerting user that information already exists -->
                                        {%if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{form.errors}}</strong>
                                        </div>
                                        {% endif %}
                                        <!-- Responsible for alerting user that information already exists -->
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Create an Account</h1>
                                            <p class="mb-30">Already have an account? <a href="{% url 'userauths:sign-in' %}">Login</a></p>
                                        </div>
                                        <form method="post" method="POST">
                                            <!-- Responsible creating a User Session (PREVENTS CROSS-SITE FORGERY [Security]) -->
                                            {% csrf_token %}
                                            <!-- Recieves/Retrieves User Information -->
                                            <div class="form-group">
                                                {{form.username}}
                                            </div>
                                            <div class="form-group">
                                                {{form.email}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password1}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password2}}
                                            </div>
                                            <div class="form-group mb-30">
                                                <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="login">Submit &amp; Register</button>
                                            </div>
                                            <p class="font-xs text-muted"><strong>Note: </strong>Your personal data will be used to support your experience throughout this website</p>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}