bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

#Written by Noe 
from core.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("vendoradmin/", include("vendoradmin.urls")),

    path("ckeditor5/", include('django_ckeditor_5.urls')),
]


# Always serve media files in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static files only needed with DEBUG=True since we're using whitenoise in production
if settings.DEBUG:
    # All the static files are stored in the roots directory in a folder called static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path, include # We need inlcude for paypal integration
from core.views import index, category_list_view, product_list_view, category_product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, add_review
from core.views import search_view, filter_product, add_to_cart, cart_view, delete_item_from_cart, update_cart, checkout, paypalCompletedView, paypalFailedView, createCheckoutSession
from core.views import  dashboard, orderDetail, defaultAddress, wishlistView, addToWishList, removeFromWishlist, contact, ajax_contact_form, save_checkout, vendor_application_form, become_vendor
from core.views import aboutUs, purchasingGuide
app_name = "core"

urlpatterns = [

    # Responsible for creating URL patterns on the browser
    # Example, bookstore.com/hardcover/special

    # We leave the bottom an empty string because we want the  
    # domain alone to direct us to the websites homepage

    # Views for Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),

    # Views for Category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

    # Vendor Views
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendors/<vid>/", vendor_detail_view, name="vendor-detail"),

    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    path("add-review/<pid>/", add_review, name="add-review"),

    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name = "filter-product"),

    #################### Cart Views  #################### 
    # Add to cart URL
    path("add-to-cart/", add_to_cart, name = "add-to-cart"),

    # Cart Page
    path("cart/",cart_view, name = "cart"),

    # Used when deleting items from cart
    path("delete-from-cart/", delete_item_from_cart, name = "delete-from-cart"),

    path("update-cart/", update_cart, name = "update-cart"),


    ####################  CHECKOUT VIEWS ####################
    # Checkout View
    path("checkout/<oid>/", checkout , name = "checkout"),

    # Save Checkout
    path("save_checkout_info/", save_checkout , name = "save_checkout_info"),

    # Additional Checkout: 
    # For stripe
    path("api/create_checkout_session/<oid>/", createCheckoutSession, name="api_checkout_session"),



    #################### Payment Views  #################### 
    # Paypal Views
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('payment-completed/<oid>/', paypalCompletedView, name="payment-completed"),

    path('payment-failed/', paypalFailedView, name="payment-failed"),


    #################### User Info Views  #################### 
    # User Dashboard Views
    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/order/<int:id>', orderDetail, name="order-detail"),
    path("make-default-address/", defaultAddress , name="make-default-address"),


    #################### Wishlists Views  #################### 
    path ("wishlist/", wishlistView, name="wishlist"),
    path("add-to-wishlist/", addToWishList, name="add-to-wishlist"), 
    path("remove-from-wishlist/", removeFromWishlist, name="remove-from-wishlist"), 


    # Contact Views
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),


    path("become-vendor/", become_vendor, name="become-vendor"),
    path("vendor-application-form/", vendor_application_form, name="vendor-application-form"),

    path("about-me/", aboutUs, name="about-me"),
    path("purchasing-guide/", purchasingGuide, name="purchasing-guide"),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

'''
# Inside of Basic URL Patterns you'll see: 
    # 1) Sign-up page
    # 2) Sign-in page
    # 3) Sign-out page

These URL patterns are responsible for the absolute basics of user functionality
'''
urlpatterns = [
    # Basic URL patterns
    path("sign-up/", views.registerView, name="sign-up"),
    path("sign-in/", views.loginView, name="sign-in"),
    path("sign-out/", views.logoutView, name="sign-out"),

    # URL below is responsible for updating user's profile
    path("profile/update/", views.profileUpdate, name="profile-update"),

]

vendoradmin/urls.py
from django.urls import path
from vendoradmin.views import vendorDashboard, vendorsProducts, addProducts, editProduct, deleteProduct
from vendoradmin.views import orders, orderDetail, changeOrderStatus, shopPage, reviews, settings, changePassword

app_name = "vendoradmin"

urlpatterns = [
    path("dashboard/", vendorDashboard, name="dashboard"),
    path("products/", vendorsProducts, name="products"),
    path("add_product/", addProducts, name="add_product"),
    path("edit_product/<pid>/", editProduct, name="edit_product"),
    path("delete_product/<pid>/", deleteProduct, name="delete_product"),
    path("orders/", orders, name="orders"),
    path("order_detail/<id>/", orderDetail, name="order_detail"),
    path("change_order_status/<oid>/", changeOrderStatus, name="change_order_status"),
    path("shop_page/", shopPage, name="shop_page"),
    path("reviews/", reviews, name="reviews"),
    path("settings/", settings, name="settings"),
    path("change_password/", changePassword, name="change_password"),
]

core/models.py
from django.db import models
from unicodedata import decimal
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from pyexpat import model
from userauths.models import User
from taggit.managers import TaggableManager
from django_ckeditor_5.fields import CKEditor5Field
from django.db.models import Avg

STATUS_CHOICE = {

    # Users should only see the right side
    ("processing", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
}

STATUS= {

    # Users should only see the right side
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("inReview", "In Review"),
    ("published", "Published"),
}

RATING= {

    # Users should only see the right side
    ( 1, "★☆☆☆☆"),
    ( 2, "★★☆☆☆"),
    ( 3, "★★★☆☆"),
    ( 4, "★★★★☆"),
    ( 5, "★★★★★"),
}
########################
# Create your models here.
def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="cat", alphabet="abcdefg12345")
    title = models.CharField(max_length=100, default="Category Item")
    
    # responsible for thumbnail of products
    image = models.ImageField(upload_to="categories", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title

########################
class Tags(models.Model):
    pass

########################

# Inside of /admin/ the moderator(superuser) will have to fill out form for user to become a vendor
class Vendor(models.Model):
    vid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="vendor", alphabet="abcdefg12345")

    vendor_title = models.CharField(max_length=100, default="Vendor name")
    vendor_profile_image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    vendor_banner = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")

    description = CKEditor5Field(null = True, blank = True, default = "Describe yourself!")
    
    vendor_address = models.CharField(max_length=100, default = "Vendor's Address")
    vendor_mobile = models.CharField(max_length=100, default = "(732) - 123 - 4567")
    
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Vendors"

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.vendor_profile_image.url))
    
    def __str__(self):
        return self.vendor_title
    
    def get_avg_rating(self):
        # Get all products from this vendor that have reviews
        product_ratings = productReview.objects.filter(product__vendor=self).aggregate(avg_rating=Avg('rating'))
        if product_ratings['avg_rating']:
            return product_ratings['avg_rating']
        return 0
    
    def get_rating_percentage(self):
        avg_rating = self.get_avg_rating()
        return (avg_rating / 5) * 100
    
    def get_review_count(self):
        # Count all reviews for products from this vendor
        review_count = productReview.objects.filter(product__vendor=self).count()
        return review_count

########################
class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=30, alphabet="abcdefg12345")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="products")
    title = models.CharField(max_length=100, default="Fahrenheit 451")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    description = CKEditor5Field(null = True, blank = True, default = "Here feel free to write anything about the book! Such as the wear, edition, covertype, and etc!")

    ###### CHANGED DEFAULT FROM FLOAT TO STR #####
    price = models.DecimalField(max_digits=10, decimal_places=2, default="9.99")
    old_price = models.DecimalField(max_digits=10, decimal_places=2, default="5.99")
       
    publishDate = models.CharField(max_length=100, default="todays date")
    stock_count = models.CharField(max_length=100, default="N/A", null=True, blank=True)
    condition = models.CharField(max_length=100, default="used", null=True, blank=True)

    product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")
    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)

    class Meta:
            verbose_name_plural = "Products"

    def product_image(self):
            return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
        
    def __str__(self):
            return self.title
    
    def get_percentage(self):
        if float(self.old_price) > 0:
            discount = 100 - (float(self.price) / float(self.old_price) * 100)
            return int(discount)
        return 0

########################
# Gives the ability to add MULTIPLE images to a single product
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images", default="product.jpg")
    product = models.ForeignKey(Product, related_name="p_images",on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
            verbose_name_plural = "Product Images"

########################
class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Put models from cart page in here 
    full_name = models.CharField(max_length=50, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)

    shipping_method = models.CharField(max_length=50, null=True, blank=True)
    trackingId = models.CharField(max_length=50, null=True, blank=True)
    trackingWebsite = models.CharField(max_length=50, null=True, blank=True)

    price = models.DecimalField(max_digits=9, decimal_places=2, default=9.99)
    money_saved = models.CharField(max_length=50, null=True, default=0.00)
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing", null=True, blank=True)

    # The bookstore is a marketplace, therefore if we have any vendors who are selling books 
    # as their full time job, we want to provide features to help them organize or manage their inventory
    # The Custom label is sort of like SKU's
    custom_label = ShortUUIDField(null=True, blank=True, length=5, max_length=20,)
    oid = ShortUUIDField(null=True, blank=True, length=5, max_length=20, alphabet="123456789")

    # Adding Coupon Feature
    coupons = models.ManyToManyField("core.Coupon", blank=True)
    class Meta:
        verbose_name_plural = "Cart Order"

########################
class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=200)
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=9, decimal_places=2, default="0.00")
    total = models.DecimalField(max_digits=9, decimal_places=2, default="0.00")

    class Meta:
        verbose_name_plural = "Cart Order Items"

    def order_img(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))
    
########################
class productReview(models.Model):
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
    product = models.ForeignKey(Product, on_delete = models.SET_NULL, null = True, related_name = 'review')
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)
     
    class Meta:
            verbose_name_plural = "Product Reviews"
    
    def __str__(self):
            return self.product.title
    
    def get_rating(self):
         return self.rating
    

########################
class wishListModel(models.Model):
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
    product = models.ForeignKey(Product, on_delete = models.SET_NULL, null = True)
    date = models.DateTimeField(auto_now_add=True)
     
    class Meta:
            verbose_name_plural = "Wishlists"
    
    def __str__(self):
            return self.product.title

########################
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    mobile = models.CharField(max_length=300, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"

########################
class Coupon(models.Model):
    code = models.CharField(max_length=15)
    discount = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    def __str__(self):

vendoradmin/forms.py
from core.models import Product, Category
from django import forms

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title', 
            'image',
            'description',
            'price',
            'old_price',
            'condition',
            'stock_count',
            'publishDate',
            'category'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': "Book Title", "class":"form-control"}),
            'description': forms.Textarea(attrs={'placeholder': "Is it a specific edition? Talk about the book", "class":"form-control", "rows": 4}),
            'price': forms.NumberInput(attrs={'placeholder': "Selling Price", "class":"form-control"}),
            'old_price': forms.NumberInput(attrs={'placeholder': "Old Price", "class":"form-control"}),
            'condition': forms.TextInput(attrs={'placeholder': "Used or New", "class":"form-control"}),
            'stock_count': forms.NumberInput(attrs={'placeholder': "How many are in stock?", "class":"form-control"}),
            'publishDate': forms.TextInput(attrs={'placeholder': "e.g: May 20, 2025", "class":"form-control"}),
            'category': forms.Select(attrs={"class":"form-select"}),
        }

templates/vendoradmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Vendor Dashboard</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="assets2/imgs/theme/favicon.svg" />
        <!-- Template CSS -->
        <link href="{% static 'assets2/css/main.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    </head>
    <body>
        <div class="screen-overlay"></div>
        <aside class="navbar-aside" id="offcanvas_aside">
            <div class="aside-top">
                <a href="{% url 'vendoradmin:dashboard' %}" class="brand-wrap">
                    <img src="https://static.vecteezy.com/system/resources/previews/011/999/627/non_2x/monitoring-icon-logo-illustration-dashboard-admin-symbol-template-for-graphic-and-web-design-collection-free-vector.jpg" class="logo"/>
                </a>
            </div>
            <nav>
                <!--   TABS ON SIDE    -->
                <ul class="menu-aside">
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'vendoradmin:dashboard' %}">
                            <i class="icon material-icons md-home"></i>
                            <span class="text">Dashboard</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'vendoradmin:products' %}">
                            <i class="icon material-icons md-shopping_bag"></i>

                            <span class="text">Products</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'vendoradmin:orders' %}">
                            <i class="icon material-icons md-shopping_cart"></i>
                            <span class="text">Orders</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'vendoradmin:shop_page' %}">
                            <i class="icon material-icons md-store"></i>
                            <span class="text">Shop Page</span>
                        </a>
                    </li>
                    <li class="menu-item ">
                        <a class="menu-link" href="{% url 'vendoradmin:add_product' %}">
                            <i class="icon material-icons md-add_box"></i>
                            <span class="text">Add product</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'vendoradmin:reviews' %}">
                            <i class="icon material-icons md-comment"></i>
                            <span class="text">Reviews</span>
                        </a>
                    </li>
                </ul>
                <hr />
                <ul class="menu-aside">
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'vendoradmin:settings' %}">
                            <i class="icon material-icons md-settings"></i>
                            <span class="text">Edit Profile</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'vendoradmin:change_password' %}">
                            <i class="icon material-icons md-lock"></i>
                            <span class="text"> Change Password </span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'userauths:sign-out' %}">
                            <i class="icon material-icons md-arrow_forward"></i>
                            <span class="text">Logout</span>
                        </a>
                    </li>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'core:index' %}">
                            <i class="material-icons md-exit_to_app"></i>
                            <span class="text">Back to Home Page</span>
                        </a>
                    </li>
                </ul>
                <br />
                <br />
            </nav>
        </aside>
        <main class="main-wrap">
            <header class="main-header navbar">
                <div class="col-search">
                </div>
                <div class="col-nav">
                    <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"><i class="material-icons md-apps"></i></button>
                    <ul class="nav">
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> 
                                {% if request.user.profile.image %}
                                <img class="img-xs rounded-circle" src="{{request.user.profile.image.url}}" alt="User" />
                                {% else %}
                                <img class="img-xs rounded-circle" src="https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2281862025.jpg" alt="User" />
                                {% endif %}    
                            </a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                                <a class="dropdown-item" href="{% url 'vendoradmin:settings' %}"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                                <a class="dropdown-item" href="{% url 'vendoradmin:orders' %}"><i class="material-icons md-receipt"></i>Billing</a>
                                <a class="dropdown-item text-danger" href="{% url 'userauths:sign-out' %}"><i class="material-icons md-exit_to_app"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </header>
            {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 3000)
                </script>
            {% block content %} 
            
            {% endblock content %}
            <!-- content-main end// -->
            <footer class="main-footer font-xs">
                <div class="row pb-30 pt-15">
                    <div class="col-sm-6">
                        <p>
                            2025 &copy; Shelf Space .
                        </p>
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end">All rights reserved to Shelf Space</div>
                    </div>
                </div>
            </footer>
        </main>
        <script src="{% static 'assets2/js/vendors/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/select2.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/perfect-scrollbar.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/jquery.fullscreen.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/chart.js' %}"></script>
        <!-- Main Script -->
        <script src="{% static 'assets2/js/main.js?v=1.1' %}" type="text/javascript"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <!-- <script src="{% static 'assets2/js/custom-chart.js' %}" type="text/javascript"></script> -->
    </body>
</html>

templates/vendoradmin/orders.html
{% extends 'vendoradmin/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}    
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Orders</h2>
            <p>Manage Your Orders</p>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                            <tr>
                            <th>#ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Total</th>
                            <th scope="col">Order Status</th>
                            <th scope="col">Payment Status</th>
                            <th scope="col">Action</th>
                        </tr>
                            
                    </thead>
                    <tbody>
                        {% for c in orders %}
                            <tr>
                                <td>#{{c.oid}}</td>
                                <td><b>{{c.full_name|title}}</b></td>
                                <td>{{c.email}}</td>
                                <td>${{c.price}}</td>
                                <td><span class="badge alert-secondary">Pending</span></td>
                                {% if c.paid_status == True %}
                                    <td><span class="badge alert-success"></span>Paid</td>
                                {% else %}
                                    <td><span class="badge alert-danger">Not Paid</span></td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'vendoradmin:order_detail' c.id %}" class="btn btn-md rounded font-sm">View Detail</a>
                                </td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
            <!-- table end -->
        </div>
    </div>
</section>


{% endblock content %}

templates/vendoradmin/products.html
{% extends 'vendoradmin/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Products List</h2>
            <p>Manage all your books from here</p>
        </div>
        <div>
            <a href="{% url 'vendoradmin:add_product' %}" class="btn btn-primary btn-sm rounded">Create Product</a>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-body">
            {% for p in all_products %}
            <article class="itemlist">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                        <a class="itemside" href="{% url 'core:product-detail' p.pid %}">
                            <div class="left">
                                <img src="{{p.image.url}}" style="width: 100px; height: 100px; object-fit: cover; border-radius: 15px;" class="img-sm img-thumbnail" alt="Item" />
                            </div>
                            <div class="info">
                                <h6 class="mb-0">{{p.title}}</h6>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-4 col-price"><span>${{p.price}}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-status"><span class="badge  alert-dark">{{p.product_status|title}}</span></div>
                    <div class="col-lg-1 col-sm-2 col-4 col-date"><span>{{p.date}}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                        <a href="{% url 'vendoradmin:edit_product'  p.pid %}" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                        <a href="{% url 'vendoradmin:delete_product' p.pid  %}" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </a>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}