bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

#Written by Noe 
from core.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("vendoradmin/", include("vendoradmin.urls")),

    path("ckeditor5/", include('django_ckeditor_5.urls')),
]


# Always serve media files in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static files only needed with DEBUG=True since we're using whitenoise in production
if settings.DEBUG:
    # All the static files are stored in the roots directory in a folder called static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path, include # We need inlcude for paypal integration
from core.views import index, category_list_view, product_list_view, category_product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, add_review
from core.views import search_view, filter_product, add_to_cart, cart_view, delete_item_from_cart, update_cart, checkout, paypalCompletedView, paypalFailedView, createCheckoutSession
from core.views import  dashboard, orderDetail, defaultAddress, wishlistView, addToWishList, removeFromWishlist, contact, ajax_contact_form, save_checkout, vendor_application_form, become_vendor
from core.views import aboutUs, purchasingGuide
app_name = "core"

urlpatterns = [

    # Responsible for creating URL patterns on the browser
    # Example, bookstore.com/hardcover/special

    # We leave the bottom an empty string because we want the  
    # domain alone to direct us to the websites homepage

    # Views for Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),

    # Views for Category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

    # Vendor Views
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendors/<vid>/", vendor_detail_view, name="vendor-detail"),

    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    path("add-review/<pid>/", add_review, name="add-review"),

    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name = "filter-product"),

    #################### Cart Views  #################### 
    # Add to cart URL
    path("add-to-cart/", add_to_cart, name = "add-to-cart"),

    # Cart Page
    path("cart/",cart_view, name = "cart"),

    # Used when deleting items from cart
    path("delete-from-cart/", delete_item_from_cart, name = "delete-from-cart"),

    path("update-cart/", update_cart, name = "update-cart"),


    ####################  CHECKOUT VIEWS ####################
    # Checkout View
    path("checkout/<oid>/", checkout , name = "checkout"),

    # Save Checkout
    path("save_checkout_info/", save_checkout , name = "save_checkout_info"),

    # Additional Checkout: 
    # For stripe
    path("api/create_checkout_session/<oid>/", createCheckoutSession, name="api_checkout_session"),



    #################### Payment Views  #################### 
    # Paypal Views
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('payment-completed/<oid>/', paypalCompletedView, name="payment-completed"),

    path('payment-failed/', paypalFailedView, name="payment-failed"),


    #################### User Info Views  #################### 
    # User Dashboard Views
    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/order/<int:id>', orderDetail, name="order-detail"),
    path("make-default-address/", defaultAddress , name="make-default-address"),


    #################### Wishlists Views  #################### 
    path ("wishlist/", wishlistView, name="wishlist"),
    path("add-to-wishlist/", addToWishList, name="add-to-wishlist"), 
    path("remove-from-wishlist/", removeFromWishlist, name="remove-from-wishlist"), 


    # Contact Views
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),


    path("become-vendor/", become_vendor, name="become-vendor"),
    path("vendor-application-form/", vendor_application_form, name="vendor-application-form"),

    path("about-me/", aboutUs, name="about-me"),
    path("purchasing-guide/", purchasingGuide, name="purchasing-guide"),
]

core/forms.py
from django import forms
from core.models import productReview

class productReviewForm(forms.ModelForm):
    reivew = forms.CharField(widget = forms.Textarea(attrs= {'placeholder': 'Write Review'}))

    class Meta:
        model = productReview
        fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from core.models import Product, Category, Vendor, CartOrder, CartOrderItems, wishListModel, ProductImages, productReview, Address, Coupon, becomeVendorModel
from django.db.models import Count, Avg, Min, Max
from taggit.models import Tag
from django.template.loader import render_to_string
from core.forms import productReviewForm
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required

# added serializers for wishlist inorder for function.js remove wishlist function/feature to work properly
# without the use of serializers will cause tons of issues with django querysets. 
from django.core import serializers
from userauths.models import Profile, ContactUs

# Not only are we dealing with Paypal for payment but we will be working with stripe
import stripe

# 

# Create your views here.
'''
For the ake of organization, no userauthenitcation view will be used in this section. 
Since I am trying to build a clean final product I want to keep domain separation a thing. 
Therefore, separating the user views not only would help us locate it easily but will help us reuse it for any future projects
'''

def index(request):
    #products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published", featured = True)
    context = {
        "products":products
    }    

    return render(request, 'core/index.html', context)  

def product_list_view(request):
    sort_by = request.GET.get("sort", "featured")  # Default sort is featured
    
    products = Product.objects.filter(product_status="published")
    
    # Apply sorting based on the sort parameter
    if sort_by == "price_low_to_high":
        products = products.order_by("price")
    elif sort_by == "price_high_to_low":
        products = products.order_by("-price")
    elif sort_by == "release_date":
        products = products.order_by("-date")
    elif sort_by == "avg_rating":
        products = products.order_by("-rating")
    else:  # Default to featured (which we'll implement as newest)
        products = products.order_by("-date")
    
    # Get min and max prices for the price filter
    min_max_price = Product.objects.filter(product_status="published").aggregate(
        price__min=Min('price'),
        price__max=Max('price')
    )
    
    # Set default values if None is returned
    if min_max_price['price__min'] is None:
        min_max_price['price__min'] = 0
    if min_max_price['price__max'] is None:
        min_max_price['price__max'] = 1000

    context = {
        "products": products,
        "min_max_price": min_max_price,
        "categories": Category.objects.all(),
        "vendors": Vendor.objects.all(),
        "current_sort": sort_by,
    }
    return render(request, 'core/product-list.html', context)


def category_list_view(request):
    sort_by = request.GET.get("sort", "featured")  # Default sort is featured
    
    categories = Category.objects.all()
    
    # Apply sorting based on the sort parameter
    if sort_by == "name_a_z":
        categories = categories.order_by("title")
    elif sort_by == "name_z_a":
        categories = categories.order_by("-title")
    # Default to featured (you can define what "featured" means for categories)
    else:
        categories = categories.order_by("id")

    context = {
        "categories": categories,
        "current_sort": sort_by,
    }
    return render(request, 'core/category-list.html', context)  

def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    sort_by = request.GET.get("sort", "featured")  # Default sort is featured
    
    products = Product.objects.filter(product_status="published", category=category)
    
    # Apply sorting based on the sort parameter
    if sort_by == "price_low_to_high":
        products = products.order_by("price")
    elif sort_by == "price_high_to_low":
        products = products.order_by("-price")
    elif sort_by == "release_date":
        products = products.order_by("-date")
    elif sort_by == "avg_rating":
        products = products.order_by("-rating")
    else:  # Default to featured (which we'll implement as newest)
        products = products.order_by("-date")

    context = {
        "category": category,
        "products": products,
        "current_sort": sort_by,
    }
    return render(request, 'core/category-product-list.html', context)  

def vendor_list_view(request):
    vendors=Vendor.objects.all()
    context = {
        "vendors":vendors,
    }
    return render(request, "core/vendor-list.html", context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    sort_by = request.GET.get("sort", "featured")  # Default sort is featured
    
    products = Product.objects.filter(vendor=vendor, product_status="published")
    
    # Apply sorting based on the sort parameter
    if sort_by == "price_low_to_high":
        products = products.order_by("price")
    elif sort_by == "price_high_to_low":
        products = products.order_by("-price")
    elif sort_by == "release_date":
        products = products.order_by("-date")
    elif sort_by == "avg_rating":
        products = products.order_by("-rating")
    else:  # Default to featured (which we'll implement as newest)
        products = products.order_by("-date")
    
    # Get categories for sidebar
    categories = Category.objects.all()
    
    context = {
        "vendor": vendor,
        "products": products,
        "current_sort": sort_by,
        "categories": categories,
    }
    return render(request, "core/vendor-detail.html", context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    reviews = productReview.objects.filter(product=product).order_by("-date")

    # average reviews view
    average_rating = productReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    # Product review form
    review_form = productReviewForm()

    p_image = product.p_images.all()

    make_review = True
    if request.user.is_authenticated:
        user_review_count = productReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False


    context = {
        "p":product,
        'review_form': review_form,
        'make_review':make_review,
        "p_image":p_image,
        "average_rating": average_rating,
        'reviews':reviews, 
        "products":products,
    }
    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
    
    context = {
        "products":products,
        "tag":tag,
    }

    return render(request, "core/tag.html", context)

def add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = productReview.objects.create(
        user=user, 
        product=product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )
    context = {
        'user': user.username, 
        'review':request.POST['review'],
        'rating':request.POST['rating'],
    }

    average_reviews = productReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
        'bool': True, 
        'context': context,
        'average_reviews':average_reviews,
        }
    )


# when searching, it's going to grab any product that contains the information the user inserted and will output the most latest added products
def search_view(request):
    query = request.GET.get("q")
    sort_by = request.GET.get("sort", "featured")  # Default sort is featured
    
    products = Product.objects.filter(title__icontains=query)
    
    # Apply sorting based on the sort parameter
    if sort_by == "price_low_to_high":
        products = products.order_by("price")
    elif sort_by == "price_high_to_low":
        products = products.order_by("-price")
    elif sort_by == "release_date":
        products = products.order_by("-date")
    elif sort_by == "avg_rating":
        products = products.order_by("-rating")
    else:  # Default to featured (which we'll implement as newest)
        products = products.order_by("-date")

    context = {
        "products": products,
        "query": query,
        "current_sort": sort_by,
    }
    return render(request, "core/search.html", context)

def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by(".-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories) > 0:
        products = Product.objects.filter(category_id_in=categories).distinct()

    if len(vendors) > 0:
        products = Product.objects.filter(vendor_id_in=vendors).distinct()

    data = render_to_string("core/async/product-list.html", {"products":products})
    return JsonResponse({"data":data})

def clean_price(price_str):
    # Check for empty string or None
    if not price_str:
        return '0'  # Return '0' for empty strings
    
    # Remove dollar sign and fix multiple decimal points
    price_str = price_str.replace('$', '')

templates/core/async/cart-list.html
<!-- Cart content for async updates -->
<div class="table-responsive shopping-summery">
    <table class="table table-wishlist">
        <thead>
            <tr class="main-heading">
                <th scope="col">Product</th>
                <th scope="col">Title</th>
                <th scope="col">Unit Price</th>
                <th scope="col" class="text-center">Quantity</th>
                <th scope="col">Subtotal</th>
                <th scope="col" class="">Refresh</th>
                <th scope="col" class="end">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for p_id, item in cart_data.items %}
            <tr class="pt-30">
                <td class="image product-thumbnail pt-40"><img src="{{item.image}}" alt="#"></td>
                <td class="product-des product-name">
                    <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{%url 'core:product-detail' item.pid %}">{{item.title}}</a></h6>
                </td>
                <td class="price" data-title="Price">
                    <h4 class="text-body">${{item.price|floatformat:2}}</h4>
                </td>
                <td class="text-center detail-info" data-title="Stock">
                    <div class="mr-15">
                        <input type="number" class="product-qty-{{p_id}}" value="{{item.qty}}" min="1">
                    </div>
                </td>
                <td class="price" data-title="Price">
                    <h4 class="text-brand">${% widthratio item.price 1 item.qty %}</h4>
                </td>
                <td class="action text-center" data-title="Refresh">
                    <a style="border: none; background: none;" class="text-body update-product" data-product="{{p_id}}">
                        <i class="fi-rs-refresh"></i>
                    </a>
                </td>
                <td class="action text-center" data-title="Remove">
                    <a style="border: none; background: none;" class="text-body delete-product" data-product="{{p_id}}">
                        <i class="fi-rs-trash"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

templates/core/async/product-list.html
{% for p in products %}
<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
    <div class="product-cart-wrap mb-30">
        <div class="product-img-action-wrap">
            <div class="product-img product-img-zoom">
                <a href="{% url 'core:product-detail' p.pid %}">
                    <img class="default-img" src="{{ p.image.url }}" alt="" />
                    <img class="hover-img" src="{{ p.image.url }}" alt="" />
                </a>
            </div>
            <div class="product-action-1">
                <a aria-label="Add To Wishlist" class="action-btn" href="{% url 'core:wishlist' %}"><i class="fi-rs-heart"></i></a>
                <a aria-label="Quick view" class="action-btn" href="{% url 'core:product-detail' p.pid %}" class="action-btn"><i class="fi-rs-eye"></i></a>
            </div>
            <div class="product-badges product-badges-position product-badges-mrg">
                <span class="hot">-{{p.get_percentage|floatformat:0}}</span>
            </div>
        </div>
        <div class="product-content-wrap">
            <div class="product-category">
                <a href="#">{{ p.category.title }}</a>
            </div>
            <h2><a href="{% url 'core:product-detail' p.pid %}">{{ p.title }}</a></h2>
            <div class="product-rate-cover">
                <div class="product-rate d-inline-block">
                    <div class="product-rating" style="width: 90%"></div>
                </div>
                <span class="font-small ml-5 text-muted">({{ p.reviews.all.count }})</span>
            </div>
            <div>
                <span class="font-small text-muted">By <a href="vendor-details-1.html">{{ p.vendor.title }}</a></span>
            </div>
            <div class="product-card-bottom">
                <div class="product-price">
                    <span>{{p.price}}</span>
                    <span class="old-price">{{p.old_price}}</span>
                </div>
                <div class="add-cart">
                    <a class="add" href="{% url 'core:cart' %}"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

templates/core/async/wishlist-list.html
<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'core:index.html' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Wishlist
            </div>
        </div>
    </div>
    <div class="container mb-30 mt-50">
        <div class="row">
            <div class="col-xl-10 col-lg-12 m-auto">
                <div class="mb-50">
                    <h1 class="heading-2 mb-10">Your Wishlist</h1>
                    <h6 class="text-body">You have <span class="text-brand">{{ w|length }}</span> products wishlisted</h6>
                </div>
                <div class="table-responsive shopping-summery">
                    <table class="table table-wishlist">
                        <thead>
                            <tr class="main-heading">
                                <th class="custome-checkbox start pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                    <label class="form-check-label" for="exampleCheckbox11"></label>
                                </th>
                                <th scope="col" colspan="2">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Stock Status</th>
                                <th scope="col">Action</th>
                                <th scope="col" class="end">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for w in w %}
                            <tr class="pt-30">
                                <td class="custome-checkbox pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                    <label class="form-check-label" for="exampleCheckbox1"></label>
                                </td>
                                <td class="image product-thumbnail pt-40"><img src="{{w.product.image.url}}" alt="#" /></td>
                                <td class="product-des product-name">
                                    <h6><a class="product-name mb-10" href="{% url 'core:product-detail' w.product.pid %}">{{ w.product.title|truncatechars:30 }}</a></h6>
                                    
                                </td>
                                <td class="price d-fdlex fs-1" data-title="Price">
                                    <span class="text-brand">$</span><span class="text-brand current-product-price-{{ w.product.id }}">{{ w.product.price }}</span>
                                </td>
                                <td class="text-center detail-info" data-title="Stock">
                                    <span class="stock-status in-stock mb-0"> {% if w.product.in_stock %} In Stock {% else %} Out of Stock {% endif %}</span>
                                </td>
                                <td class="text-right" data-title="Cart">
                                    <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ w.product.id }}">
                                    <input type="hidden" class="product-pid-{{ w.product.id }}" value="{{ w.product.pid }}">
                                    <input type="hidden" class="product-image-{{ w.product.id }}" value="{{ w.product.image.url }}">
                                    <input type="hidden" class="product-id-{{ w.product.id }}" value="{{ w.product.id }}">
                                    <input type="hidden" class="product-title-{{ w.product.id }}" value="{{ w.product.title }}">
                                    <button class="btn btn-sm add-to-cart-btn" data-index="{{ w.product.id }}">Add to cart</button>
                                </td>
                                <td class="action text-center" data-title="Remove">
                                    <button style="border: none; background: none;" data-wishlist-product="{{ w.id }}"  class="text-body delete-wishlist-product"><i class="fi-rs-trash"></i></button>

                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td><p>Nothing in wishlist yet...</p></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>